name: Deploy to Akash Network

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set IMAGE variable to personal namespace (lowercase)
        run: echo "IMAGE=ghcr.io/${GITHUB_ACTOR,,}/crisis:${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE .

      - name: Push Docker image
        run: |
          docker push $IMAGE

      - name: Install Akash CLI
        run: |
          curl -s https://raw.githubusercontent.com/ovrclk/akash/master/scripts/install.sh | bash
          akash version

      - name: Deploy to Akash Network
        env:
          AKASH_KEY: ${{ secrets.AKASH_KEY }}
          AKASH_NODE: ${{ secrets.AKASH_NODE }}
          AKASH_CHAIN_ID: ${{ secrets.AKASH_CHAIN_ID }}
          AKASH_ACCOUNT_ADDRESS: ${{ secrets.AKASH_ACCOUNT_ADDRESS }}
        run: |
          echo "Using Akash CLI to deploy..."
          akash tx deployment create scripts/deploy.yaml --from $AKASH_ACCOUNT_ADDRESS --node $AKASH_NODE --chain-id $AKASH_CHAIN_ID --keyring-backend test --yes
